### ISSUE TITLE
Zero value in pop

### ISSUE THREAD

**Issue by vdemario** [scylladb/go-set#11]
Documentation of the [`Pop` function in strset](https://godoc.org/github.com/scylladb/go-set/strset#Set.Pop) says:

> If Set is empty, nil is returned.

The signature of the function is `func (s *Set) Pop() string` so a nil return is not possible. It instead returns the zero value, in this case an empty string. An empty string, however, could be a valid member of a string set.

What do you think of changing the signature of `Pop` to add a booleanv value indicating if there was an element or not, such as `https://godoc.org/github.com/standupdev/strset#Set.Pop`. It would be similar to the way maps are natively implemented.

**Comment by mmatczuk** [comment]
The problem is that this change would break the backwards compatibility with fatih/set. We could add a Pop2 function @dahankzter WDYT?

**Comment by vdemario** [comment]
Another option is to cut a new release with a bump in the major version number. This would indicate cleanly a break in the API.

**Comment by vdemario** [comment]
May I submit a PR already? We can change the signature of the function while the PR is open, what do you think?

**Comment by mmatczuk** [comment]
Hi @vdemario a PR would be good. I suggest we go with a new `Pop2` function, we want to be compatible with fatih/set.

**Comment by dahankzter** [comment]
I think Pop2 is better even if it also hurts a bit. We must also consider some consumers may already depend on v1.0.0 module although that risk is not so high yet.
